#+TITLE: Notes for anything I think of
#+AUTHOR: brickviking (yes, me!)
#+TAGS: emacs vim cheatsheet keys
* header stuff. Why do I need this?
[# 
(defun c () (interactive) (find-blogme3-sh0-if "emacsconf2019"))
(defun u () (interactive) (find-blogme-upload-links "emacsconf2019"))
;;    http://angg.twu.net/emacsconf2019.html
;; file:///home/edrx/TH/L/emacsconf2019.html
;; (eco)
;;
#]
[lua:
  require "sexp"   -- (find-blogme3 "sexp.lua")
  def [[ ECS0 1 time youtube_make_url("86yiRG8YJD0", time) ]]
  def [[ ECS  2 time,text BR()..R(ECS0(time), time).." "..text ]]
  def [[ ECSQ 2 time,text ECS(time, Q(text)) ]]
]



* Emacs
** Cock-ups
   * When starting a remote file access, don't run M-x tramp  first. Things will break.
   * A docstring is not info documentation. C-h m gives you docstrings, but go to relevant info manual for details.
** Help
   | Info for emacs                        | C-h r |                     |
   | Global info dir                       | C-h i |                     |
   | Describe current major mode           | C-h m |                     |
   | Describe key                          | C-h c | Mode sensitive      |
   | Describe binding                      | C-h b | Also mode sensitive |
   | Info Doc Search (word list or regexp) | C-h d |                     |
   |                                       |       |                     |

** Windows/Frames
   + Cycle through visible windows  C-x o
   + Focus buffer to whole window C-x 1
   + Split window Top/Bottom C-x 2
   + Split window Left/Right C-x 3
   + Open new file in another window C-x 4 f
   + Scroll other window: down C-M-v, up C-M-S-v
   + Close frame  C-x 5 0
** Buffers
   + Swap buffer  C-x b
   + List All Buffers  C-x C-b
When in buffer selection window 
   m marks, k marks for delete, x deletes, u undoes mark, U undoes all marking
   + Change encoding (GUI) by clicking mouse-1 on colon or encoding in headerline
     + -:@---      UNIX (LF 0x0A)
     + -(DOS)@---  Dos encoding (CRLF 0x0D 0x0A)
     + -(Mac)@---  Mac OS X encoding (CR  0x0D)
   + Also check [[How to set a buffer's line-encoding from text mode]]
** org mode
+ Tab on */+ line expands/compacts tree
  1) First time: expand one level below point without exposing text
  2) Second time: expand all levels below point including text
  3) Third time: compact all levels below point back to heading
+ S-tab   global expansion
  1) expand all headings without exposing text
  2) expand entire document (headings, text, etc)
  3) compact entire document to top headings
+ Shift-Right on list: +/*/1./1)/-
+ Shift-Up/Down on header (change priority #A/#B/#C, to customize this: #+PRIORITIES A E E)
+ M-Up/Down Shift line above/below
+ M-Left/Right Promote/demote heading
+ M-S-Left/Right Promote/demote heading and everything below
+ Some tags don't appear to work except for export/archive mode, including #+TAGS
+ Checkboxes [ ] [X]
+ demarcate block (wrap it in BEGIN_SRC..END_SRC)   C-c C-v d	(org-babel-demarcate-block)
+ export C-c C-e, will ask for format
+ Shift-right/left (on header) Cycle through TODO/DONE/nothing or defined tags, see [[header_tags]]
+ For tables, expand the header_tags section.
*** header_tags
  | Name          | Type                   | Description                          |
  |---------------+------------------------+--------------------------------------|
  | #+TITLE       | <string>               | Title of document                    |
  | #+AUTHOR      | <string>               | Who wrote this originally            |
  | #+CREATOR     | <string>               | No idea why this differs from AUTHOR |
  | #+TAGS        | <words>{1,}            | tag categories                       |
  | #+DATE        | <timestamp>            | date of document                     |
  | #+DESCRIPTION | <string>               | Short precis of what it is           |
  | #+SEQ_TODO    | <string> [<string>]... | Before pipe, one colour.             |
  |               |                        | After pipe, completed colour         |
  
*** tags
  | Name        | Description |                                     |
  |-------------+-------------+-------------------------------------|
  | #+BEGIN_SRC | [lang]      | Source code block - can be tangled  |
  | #+END_SRC   |             | Closes it                           |
  | #+SCHEDULED | <timestamp> | When is this meant to be started    |
  | #+COMPLETED | <timestamp> | When this actually got completed    |
  | #+DEADLINE  | <timestamp> | When it's absolutely got to be done |
  |-------------+-------------+-------------------------------------|
  |             |             |                                     |
*** inline images
+ Inline images in org mode: toggle visibility with C-c C-x C-v
+ Change size of inline org images
  + Don't forget to eval (setq org-image-actual-width nil)
  + with #+ATTR_ORG: :height ... :width ...
** magit
There's a lot more that I haven't added, perhaps (info "(magit)Top") will help out if you
have magit installed.
From the magit buffer, you can do the following things. Most of them will prompt for other
things if they need them. Usually you put your cursor on the object you want to affect, or
on the section header if you wish to affect all files in that category.
NB: the section header often has a > in the fringe, but this is not visible in textmode.
*** Adding untracked file        s (stage)
Simply put your cursor on the file you want to stage, hit s. The file should then shift into "Staged
changes", ready for you to commit. This roughly duplicates "git add file.blah".

TODO: No idea how to add a directory from magit yet.
*** Staging an unstaged file     s (stage)
Same as above, except for a file that's already part of the git repository.
*** Committing staged files      c (commit)
Will request how you want to commit, hit c again to bring up an editor window. Provide a single line
commit message. If you want to add more lines, leave a blank line after the single line as follows:
#+BEGIN_EXAMPLE diff
Initial commit message

This is the next line for a multi-line comment.
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is up to date with 'origin/master'.
#
# Changes to be committed:
#	modified:   notes.org
#
# Untracked files:
#	notes.org~
#

#+END_EXAMPLE
*** Show diff against files      d (diff)

*** Refresh magit buffer         g (magit-refresh)
This refreshes the magit status buffer once you've made some changes within the project.
*** Expand/hide section          <TAB>
Type TAB to expand or hide the section at point.
*** Visit change/commit          <RET>
Type RET to visit the change or commit at point.
*** Turn region into list        C-c -
*** Turn region into headers     C-c *
** erc
   + quit server: C-c C-x
   + Join channel:  C-c C-j
   + Change to channel with activity: C-c C-Space
** Recommended Plugins
  flyspell - expensive on computation
  wc-mode
  writegood
** Snippets from freenode#emacs
*** How to search/replace all * at B.O.L. with the same number of #
<laertus> i need some search and replace help...  [19:53]
<laertus> i'd like to replace all the leading *'s in a buffer with the same number of #'s
<laertus> so if a line starts with *** i'd like to replace that part of the line with ###
<laertus> and if it starts with ** i'd like to replace the ** with ## etc
<laertus> i can write a function to do this, but was hoping there'd be an easier way  [19:54]
<Viking667> not really sure. I'd have done it in vim with :%s/***/###/cg  [19:55]
<Viking667> but that's not the emacs way, and that's not taking account of the escaping too.
<laertus> yeah, that'll only work for exactly 3 ***'s and it can be done exactly that way in evil
<laertus> i'm looking for a more general solution that'll work for any number of leading *'s
<dale> laertus: How about: M-x query-replace-regexp RET ^\*+ RET \,(make-string (length (match-string 0)) ?#) RET  [20:08]
<Qudit314159> It works here  [20:13]
<Viking667> I'll have to check that on my buffer.
<laertus> someone gave me a vim solution on #vim:  %s/^\*\+/\=substitute(submatch(0), '*', '#', 'g')  [20:14]
<laertus> unfortunately, i don't think that'll work with evil, as evil doesn't implement vim's regex engine, and instead just uses emacs' regex engine  [20:15]
<Qudit314159> Well, dale's should work. If it doesn't, something else is wrong I'd say
<dale> laertus: Yeah, I tested mine here, it works.  Point was before the text you wanted to replace, right?
<laertus> it's probably something to do with my emacs config  [20:17]
<Viking667> and it works fine for me (I'm pretty much vanilla emacs)
<dale> laertus: I can't think of another way to do it with Emacs regexps.
<laertus> well, thank you, dale, it's a good solution
<dale> You... might be able to do it if you had PCRE and a look-behind assertion, but I'm not sure since I can't remember if PCRE does variable-width look-behind.  [20:19]
<Viking667> i.e. copy query-replace-regexp, paste it into M-x, type in ^\*+, hit RET, copy the last long bit, paste it in etc etc.
<piyo> in elisp: (query-replace-regexp "^\\*+" '(replace-eval-replacement replace-quote (make-string (length (match-string 0)) 35)) nil nil nil nil nil)  [20:23]
<piyo> also, works for me if I turn off pcre-mode and on, as well. yeah  [20:25]
<Viking667> I might snip that and stuff it into my notes.org  [20:26]
<laertus> piyo: that works for me but it prompts me to confirm every replacement  [20:27]
<piyo> press ! to confirm all
<laertus> ah, ok.. thanks  [20:28]
<piyo> press ? for more info in the query-replace-regexp
<laertus> this vim solution:  :g/^\*/norm! vt r#  [20:29]
<piyo> to me, doing that (make-string...) thing in the minibuffer makes me want more guided help.
<laertus> makes me realize that this could be done with a macro
<laertus> just search for a * at the beginning of the line, and then replace all *'s until the first space with #'s  [20:30]
<laertus> and repeat the macro until done
<piyo> the same thing with tramp, can't remember the incantation. Can't you just transient/dialog box the url for me?
*** How to split frame into four, don't forget to keybind this, say to C-x 4 w
#+BEGIN_SRC emacs-lisp
(defun window-split-four ()
  (interactive)
  (delete-other-windows)
  (with-selected-window (split-window-right)
    (split-window))
  (split-window))
#+END_SRC
*** How to set a buffer's line-encoding from text mode
<spudpnds> C-x RET f {unix,mac,dos}  M-x set-buffer-file-coding-system
<spudpnds> https://www.emacswiki.org/emacs/EndOfLineTips
* Vim
** Exiting
   Quitting                       :q
   Quitting with multiple files   :qa
   Write file and quit            :wq
   Quitting without writing       :q!
** Opening files
   Edit new file in buffer        :e <filename>
   Insert file at cursor          :r <filename>
   Insert command output          :r !command (won't take inputo)
** Diffing files
   two ways. First, from commandline:
     vimdiff firstfile secondfile
   and within vim:
   :vert diffsplit other-file
   [c    jump to next change
   ]c    jump to previous change
** Windows
   Split window below   :sp
   Split window beside  :vsp
   Switch windows down/up/left/right  C-w <down>/...
   Swap windows    C-w C-w
** Help
  Top of help   :help
  Help on a topic    :help "searchterm"
* Music
** Classical
  + Erik Satie: Gymnopedies, gnossiennes et sarabandes (1:05:19) https://www.youtube.com/watch?v=5pyhBJzuixM
    + [P Tracklist:
       [ECSQ 00:00:00 3 Sarabandes (1887): No. 1 ]
       [ECSQ 00:05:33 3 Sarabandes (1887): No. 2 ]
       [ECSQ 00:10:33 3 Sarabandes (1887): No. 3 ]
       [ECSQ 00:14:47 3 Gymnopédies (1889): No. 1: Lent et douloureux ]
       [ECSQ 00:18:27 3 Gymnopédies (1889): No. 2: Lent et triste ]
       [ECSQ 00:21:45 3 Gymnopédies (1889): No. 3: Lent et grave ]
       [ECSQ 00:24:38 Gnossiennes 1-3 (1890): No. 1 ]
       [ECSQ 00:28:45 Gnossiennes 1-3 (1890): No. 2 ]
       [ECSQ 00:30:45 Gnossiennes 1-3 (1890): No. 3 ]
       [ECSQ 00:34:11 Gnossiennes 4-6 (1889-1897): No. 4 ]
       [ECSQ 00:37:02 Gnossiennes 4-6 (1889-1897): No. 5 ]
       [ECSQ 00:39:53 Gnossiennes 4-6 (1889-1897): No. 6 ]
       [ECSQ 00:41:27 2 Préludes du nazaréen (1892): No. 1, assez lent ]
       [ECSQ 00:46:09 2 Préludes du nazaréen (1892): No. 2, assez lent ]
       [ECSQ 00:49:15 2 Prélude de la porte Héroique du ciel (1894) ]
       [ECSQ 00:53:00 2 Pièces froides (1897), No. 1: Airs a faire fuir: D’une manière très particulaire ]
       [ECSQ 00:55:59 2 Pièces froides (1897), No. 1: Airs a faire fuir: Modestemente ]
       [ECSQ 00:57:42 2 Pièces froides (1897), No. 1: Airs a faire fuir: S’inviter ]
       [ECSQ 01:00:45 No 2: Danses de travers: En y regardent à deux fois ]
       [ECSQ 01:01:39 No 2: Danses de travers: Passer ]
       [ECSQ 01:02:25 No 2: Danses de travers: Encore ]
       [ECSQ 01:03:47 Petite ouverture à danser (1900) ]
      ]
** Programming music
***  Channel: https://www.youtube.com/channel/UCMXHtrkazQjeCOteE4sof8g
  + List: https://www.youtube.com/playlist?list=PLEM4vOSCprStzppPemEYAF6ZEUrQYj5N5
  + Programming BIOHAZARD edition #14 (1'01'01) https://www.youtube.com/watch?v=ZzRnX4UNJso
  + Programming LIQUID edition #21 (56"31) https://www.youtube.com/watch?v=GOaohYSg0m4
  + FOCUS Coding Music #15 (1'13"04) https://www.youtube.com/watch?v=cQ-a18zEBmI
  + 
** Soundtracks
  + Age of Mythology soundtrack (46"32) https://www.youtube.com/watch?v=TGXwvLupP5A
  + Factorio complete soundtrack (1'00"53) https://www.youtube.com/watch?v=T6OZrUbLJ1M
  + Hyper Light Drifter - complete OST (2'19"21) https://www.youtube.com/watch?v=bq7a_ktfYck
  + Mirror's Edge - Catalyst (5'13"10) https://www.youtube.com/watch?v=2fb5_zVk2gY
  + Ori and the Will of the Wisps (3'02") https://www.youtube.com/watch?v=eCbyqm9jcBA
  + Rimworld Complete Soundtrack https://www.youtube.com/watch?v=TXQBHblSCIc
  + Rimworld Royalty complete soundtrack  https://www.youtube.com/watch?v=PG-phyoElKU
  + Sid Meier's Civilization 6 Complete Soundtrack (4'21"21) https://www.youtube.com/watch?v=cb922Sry_DI
  + Sid Meier's Civilization: Beyond Earth (2'59"31) https://www.youtube.com/watch?v=N4mPA-tPvtc
  + Sim CITY 3000 Soundtrack (1'02"01) https://www.youtube.com/watch?v=qkXOxLpdMds
  + Complete Sim CITY 3000 Soundtrack (1'52"21) https://www.youtube.com/watch?v=k3FsVvwbAlw

*** Starbound soundtrack
Tracklist:
Horsehead Nebula - 0:00
Stellar Formation - 7:36
Eridanus Supervoid - 15:25
Haiku - 7:36 - 0:22:59
Cygnus X1 - 30:34
Psyche - 43:57
Large Magellanic Cloud - 49:22
Epsilon Indi - 0:55:36
Hymn to the Stars - 1:06:34
Europa - 1:11:12
Atlas - 1:17:16
Casiopeia - 1:21:23
Mercury - 1:27:28
Temple of Kluex - 1:33:54
Mira - 1:42:30
Procyon - 2:02:35
Blue Straggler - 2:11:44
Nomads (Passacaglia) - 2:17:27
Accretion Disc - 2:27:35
Tranquility Base - 2:32:33
Vast, Immortal Suns - 2:44:28
The Apex - 2:48:33
The Deep - 2:55:47
Drosera - 3:02:56
Error 0xBFAF000  - 3:11:14
Event Horizon - 3:14:24
Gravitational Collapse - 3:21:40
I Was the Sun (Before it was Cool) - 3:26:12
Impact Event - 3:31:10
M54 - 3:38:06
Starbound - 3:48:44
Ultramarine - 3:59:14
Via Aurora - 4:01:48
Glacial Horizon - 4:04:19
Scorian Flow - 4:07:55
Forsaken Grotto - 4:11:00
Stellar Acclimation - 4:14:27
Jupiter - 5:56 - 4:17:46
Arctic Battle 1 - 4:23:42
Arctic Battle 2 - 4:26:06
Arctic Battle 3 - 4:28:01
Arctic Constellation 1 - 4:29:40
Arctic Constellation 2 - 4:40:44
Arctic Exploration 1 - 4:50:09
Arctic Exploration 2 - 4:54:25
Crystal Battle 1 - 4:58:25
Crystal Exploration 1 - 5:01:34
Crystal Exploration 2 - 5:04:38
Desert Battle 2 - 5:08:59
Desert Exploration 1 - 5:12:37
Desert Exploration 2 - 5:15:07
Forest Battle 1 - 5:18:13
Forest Battle 2 - 5:20:39
Forest Battle 2 (alternative) - 5:24:16
Forest Exploration 1 - 5:27:52
Forest Exploration 2 - 5:31:52
Forest - 5:35:49
Glitch - 5:37:01
Ice Constellation 2 demo - 5:40:21
Inviolate - 5:49:46
Lava Exploration 1 - 5:52:33
Lava Exploration 2 - 5:55:53
Ocean Battle 1 - 6:00:41
Ocean Exploration 1 - 6:02:03
Ocean Exploration 2 - 6:06:06
On the Beach at Night - 6:09:29
Planetarium -  6:13:46
Tentacle Battle 1 - 6:18:04
Tentacle Exploration 1 - 6:19:30
Tentacle Exploration 2 - 6:22:10
Constellation 1 (8 different versions) - 6:25:16
** Weird stuff
  + Philip Glass - Music From The Hours (42"44) https://www.youtube.com/watch?v=heu9tD0dzkY
** Social
  + Uncomfortable conversations with a black man - Petuma Police Force (22"32) https://www.youtube.com/watch?v=pM-HpZQWKT4
* Programming
** Codemy (normally payware)
    + Using MySQL Databases With Python Course (1'10"09) https://www.youtube.com/watch?v=yOmxJbZjTnU
** FreeCodeCamp.org
   Youtube Channel:  https://youtube.com/c/freecodecamp
*** C++
    + C++ Tutorial for beginners - Full Course (4'01"19) https://www.youtube.com/watch?v=vLnPwxZdW4Y
*** C#
    + C# Tutorial - full course for beginners (4'31"09) https://www.youtube.com/watch?v=GhQdlIFylQ8
*** Git
    + Git and Github for beginners - crash course () https://www.youtube.com/watch?v=RGOj5yH7evk&t=228s
*** HTML 5
    + HTML 5 full course - design website in two hours (2'02"32) https://www.youtube.com/watch?v=pQN-pnXPaVg
*** Java
    + Learn Java 8 - Full tutorial for beginners (9'32"32) https://www.youtube.com/watch?v=grEKMHGYyns
*** Javascript
    + Learn Javascript - Full course for beginners, (3'26"43) https://www.youtube.com/watch?v=PkZNo7MFNFg 
*** Penetration Testing
    + Full Ethical Hacking course (14'51"14) https://www.youtube.com/watch?v=3Kq1MIfTWCE
*** Python
    + Learn Python - Full course for beginners, (4'26"52) https://www.youtube.com/watch?v=rfscVS0vtbw
    + Python for everybody - Full university python course (13'40"10) https://www.youtube.com/watch?v=8DvywoWv6fI
*** SQL
    + SQL tutorial - Full database course for beginners (4'20"39) https://www.youtube.com/watch?v=HXV3zeQKqGY 
**** Postgresql
     + Learn PostGreSQL Tutorial (4'19"34)  https://www.youtube.com/watch?v=qw--VYLpxG4
